#!/usr/bin/env bash

# Workspaces
bspc monitor -d 1 2 3 4 5 6 7 8 9 

# Window rules
bspc rule -a Xfce4-appfinder state=floating

# Window gap and padding
bspc config window_gap		  10
bspc config top_padding 	  10
bspc config bottom_padding 	  30
bspc config left_padding 	  10
bspc config right_padding 	  10

bspc config border_width 	  0

bspc config split_ratio 	  0.55
bspc config borderless_monocle    true
bspc config single_monocle 	  true
bspc config gapless_monocle 	  true
bspc config focus_follows_pointer true

# Kill all the autostart programs first
killall sxhkd
killall pnmixer
killall connman-gtk
killall nm-applet 
killall picom
# killall xcompmgr
killall dunst
# killall xfce4-panel
# killall polybar
killall ibus-daemon
killall emacs

# Key binding daemon
sxhkd &

# Wallpaper
nitrogen --restore &
# wpg -s /home/ritux/Documents/repos/wallpapers/maller/pyramid.jpg
# feh --bg-fill ~/Pictures/photo-1530890289114-8385d3901f84.jpg
#feh --bg-fill ~/Pictures/wallpapers/wallpapers/maller/astronomy.jpg

# Compositor
# picom --experimental-backends & 
# xcompmgr -c &

# Authentication
lxsession &

# Notifications
dunst &

# Network Manger applet
# connman-gtk &

# Sound applet
pnmixer &

# Power manager for laptop battery power management
xfce4-power-manager &

# Xfce4-panel
# ~/.config/xfce4/launch &

# Polybar
~/.config/polybar/launch

# Emacs daemon server 
emacs --daemon &

# Start ibus
ibus-daemon &
