#!/usr/bin/env bash

# Workspaces
bspc monitor -d 1 2 3 4 5 6 7 8 9

# Window rules
bspc rule -a Xfce4-appfinder state=floating

# Window gap and padding
bspc config window_gap 10
bspc config top_padding 40

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true

# Kill running processes
killall sxhkd
killall pnmixer
killall nm-applet
killall picom
killall dunst
killall xfce4-panel
# killall polybar
killall alttab

# Window switcher
alttab &

# Key binding daemon
sxhkd &

# Wallpaper
nitrogen --restore &
# wpg -s /home/ritux/Documents/repos/wallpapers/maller/pyramid.jpg
# feh --bg-scale ~/Documents/repos/wallpapers/maller/pyramid.jpg

# Compositor
picom &

# Authentication
mate-polkit &

# Notifications
dunst &

# Network Manger applet
nm-applet &

# Sound applet
pnmixer &

# Power manager for laptop battery power management
xfce4-power-manager &

# Xfce4-panel
~/.config/xfce4/launch &

# Polybar
# polybar mainbar-bspwm &

# Emacs daemon server 
emacs --daemon &
