#!/usr/bin/env bash

# Workspaces
bspc monitor -d 1 2 3 4 5 6 7 8 9 

# Window rules
bspc rule -a Xfce4-appfinder state=floating

# Window gap and padding
bspc config bottom_padding 	  10
bspc config top_padding 	  25
bspc config right_padding 	  5
bspc config left_padding 	  5
bspc config window_gap	          15

bspc config border_width 	  2

bspc config split_ratio 	  0.55
bspc config borderless_monocle    false
bspc config single_monocle 	  false
bspc config gapless_monocle 	  false
bspc config focus_follows_pointer true

# BSPWM coloring
#bspc config normal_border_color	  "#427b58"
bspc config active_border_color	  "#689d6a"
bspc config focused_border_color  "#689d6a"
bspc config presel_feedback_color "#8ec97c"

# Kill all the autostart programs first
killall sxhkd
killall pnmixer
killall connman-gtk
killall nm-applet 
killall picom
# killall xcompmgr
killall dunst
# killall xfce4-panel
killall polybar
killall ibus-daemon
killall emacs

# Key binding daemon
sxhkd &

# Wallpaper
nitrogen --restore &
# wpg -s /home/ritux/Documents/repos/wallpapers/maller/pyramid.jpg
# feh --bg-fill ~/Pictures/photo-1530890289114-8385d3901f84.jpg
#feh --bg-fill ~/Pictures/wallpapers/wallpapers/maller/astronomy.jpg

# Compositor
# picom --experimental-backends & 
# xcompmgr -c &

# Authentication
lxsession &

# Notifications
dunst &

# Network Manger applet
# connman-gtk &

# Sound applet
pnmixer &

# Power manager for laptop battery power management
xfce4-power-manager &

# Xfce4-panel
# ~/.config/xfce4/launch &

# Polybar
polybar example &

# Emacs daemon server 
emacs --daemon &

# Start ibus
ibus-daemon &

# High dpi
xrdb load ~/.Xresources &
